name: Flutter

on:
  # Runs this action when you push on main branch
  push:
    branches: [ "main" ]
  # Runs this when a PR against main is created
  pull_request:
    branches: [ "main" ]

jobs:
  flutter_job:

    # The machine, we can also use windows-latest or ubuntu-latest
    # We are choosing macos-latest because we will be also building for iOS
    runs-on: macos-latest

    steps:
      # Clones the project on the machine
      - uses: actions/checkout@v4

      # Installs flutter and related dependency on this machine
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      # Fetches proj dependencies from pub
      - name: Install dependencies
        run: flutter pub get
